# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_updateMohe

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_updateMohe
jobs:
  build:
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
#      - name: Set up Python 3.7
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.7
#      - name: '等待运行'
#        run: |
#              python3 accwait.py 0.1 0.1 59
              
      - name: '运行 【更新5G超级盲盒助力码】'
        run: |
          node updateShareCode.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
    
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git add .
          git commit -m "update by Action" -a || echo "Nothing to update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
